### ISSUE TITLE
Basic Flash Card Display

### ISSUE THREAD

**Issue by dverhas** [FrozenSquirrels/polyglot#1]
A very simple website that looks something like a flash card. 
Show the English word "Hello" and the Hindi word "Namasthe" for an English speaker to read and pronounce it.

**Comment by rsuhaibani** [comment]
Do you think that we gonna make it as images or just text?
Do we need to attach an image with each word?

**Comment by dverhas** [comment]
I vote for no images in this first version. Text only.

**Comment by rsuhaibani** [comment]
:+1:

**Comment by jacobdierkens** [comment]
I agree! Let's keep this simple. We should get something up and running then continue to build and improve on it.

**Comment by nathanbreitsch** [comment]
Here is my first attempt: http://frozensquirrels.pythonanywhere.com/index.html

**Comment by rsuhaibani** [comment]
Nice attempt.
Which editor have used?
