### ISSUE TITLE
Build Testing Suite

### ISSUE THREAD

**Issue by sonofab1rd** [FrozenSquirrels/polyglot#11]
Testing team should build a test suite to ensure that the site performs correctly.

**Comment by safashubbar** [comment]
I am working on it but I faced some errors, I will check it with the Professor.

**Comment by rsuhaibani** [comment]
Any one needs to setup the selenium for the unit testing should check the wiki, I have wrote the right instructions there...

**Comment by safashubbar** [comment]
Thanks
