### ISSUE TITLE
Write sprint schedule

### ISSUE THREAD

**Issue by jacobdierkens** [FrozenSquirrels/polyglot#12]
Map out the sprint schedule for the remainder of the semester. Make sure that sprint tasks are prioritized and enough team members are assigned to each task to ensure they are complete.

**Comment by dverhas** [comment]
Just an FYI on sprint planning. You only need your sprint details 1 or 2 weeks out. That way if priorities change you don't have to re-juggle everything, also the people working on the tasks shouldn't care what they work on and they can just take the next thing off the list. 

Having a long term (muti-week) vision is still needed an beneficial however, but that doesn't need to be in great detail.

**Comment by jacobdierkens** [comment]
Thanks David! That makes perfect sense. It wouldn't be very agile if we mapped everything out in great detail! I'll leave the schedule the way it is (high level overview) in the wiki under schedule.
