### ISSUE TITLE
Requirements Documents

### ISSUE THREAD

**Issue by nathanbreitsch** [FrozenSquirrels/polyglot#14]
This is extremely important, not only because we have to submit this for a grade, but because it will allow us to get stuff done in the next few weeks by giving us a set of easy, actionable steps.  (right now, we're pretty disorganized, not on sprint schedule, no commits on github this week, and people aren't sure what they're doing)

To be the most useful, It should consist of bite sized requirements that can be developed by different developers in parallel (for the most part) in a short period of time (hopefully a few hours)

Examples:

Landing Page:
   -ridiculously good looking
   -says what polyglot is all about
   -loads from the root url (move other stuff elsewhere)
   -provides link to navigation page

Navigation Page:
   -pretty good looking
   -lists set of lesson/practice categories or whatever
   -provides links to lesson/practice for each category

Image Selection Prompt Type
   -shows user word and image
   -user selects image
   -rewards user for correct response, ridicules user for incorrect response

and so on...

Work with leadership, marketing, and whoever else is in charge of making product design decisions.  (See link below for roster)
https://github.com/FrozenSquirrels/polyglot/wiki/Team

And publish your requirements docs on the wiki or something.  We will then populate the backlog with documents.

Good luck, the team depends on you.

**Comment by sravankmr** [comment]
I will work on nav. page requirments david
