### ISSUE TITLE
Managing Social Networks Accounts

### ISSUE THREAD

**Issue by rsuhaibani** [FrozenSquirrels/polyglot#20]
We need someone who can manage our social networks accounts created here: https://github.com/FrozenSquirrels/polyglot/wiki/Facebook-&-Twitter-page

**Comment by dverhas** [comment]
Marketing (@sundeep15, @abhishekgupta02081989) please take over the these social media/advertising accounts.

**Comment by rsuhaibani** [comment]
@sundeep15 @abhishekgupta02081989 please send me an email so I can send you the user and password for each account...

**Comment by sundeep15** [comment]
spadman1@kent.edu
sandeep.sam15@gmail.com

**Comment by abhishekgupta02081989** [comment]
abhishekgupta02081989@gmail.com

**Comment by rsuhaibani** [comment]
@sundeep15 @abhishekgupta02081989 Do you both have a Facebook account? if yes can you send me the email that is attached with your accounts? since I am not able to assign you as the page admins...

**Comment by abhishekgupta02081989** [comment]
Facebook ID : abhishekgupta345@gmail.com

**Comment by sundeep15** [comment]
sandeep.reddy.p.15@gmail.com

**Comment by rsuhaibani** [comment]
Yours is done, thank you.

**Comment by rsuhaibani** [comment]
You are both admins now.

**Comment by sundeep15** [comment]
Thank you ,

**Comment by rsuhaibani** [comment]
I will send you the twitter account login information by email..
