### ISSUE TITLE
Regarding the Architecture Document 

### ISSUE THREAD

**Issue by rsuhaibani** [FrozenSquirrels/polyglot#25]
Here is the professor respond about the **architecture document** that I have posted before in the wiki: 
> Hi,
> It certainly looks like a good start. It doesn’t tell the entire story, but combined with the vision statement and the requirements document, it will do nicely. 

> Best wishes,

> Dr. DeLozier

Thoughts or comments?

**Comment by hananmuhajab** [comment]
@rsuhaibani 
may be we can add some objects to cove all parts in our project :+1:
