### ISSUE TITLE
Regarding using Google AdSense as a revenue for our project 

### ISSUE THREAD

**Issue by rsuhaibani** [FrozenSquirrels/polyglot#26]
I was trying to create a Google AdSense code for our page frozensquirrels.pythonanywhere.com but unfortunately we will not be able to use it for the reason that appears in red in the following screenshot: 

![screen shot 2015-04-05 at 5 29 11 pm](https://cloud.githubusercontent.com/assets/8633667/6998760/d525ece2-dbb9-11e4-8ad9-779d8ab44da0.png)

**Comment by jacobdierkens** [comment]
David is going to purchase an available domain name so that we can use google ad sense.

**Comment by rsuhaibani** [comment]
After using the purchased domain name, the problem is solved.. we just need to wait for their review... 
![screen shot 2015-04-13 at 5 57 08 pm](https://cloud.githubusercontent.com/assets/8633667/7126367/9fad6736-e206-11e4-949a-69aa76422437.png)

**Comment by rsuhaibani** [comment]
Our application has been successfully reviewed.
