### ISSUE TITLE
Research learning and Memory 

### ISSUE THREAD

**Issue by dverhas** [FrozenSquirrels/polyglot#3]
There are many ways to learn and to remember things. 

There is research out there on different strategies, tips, and tools to learn languages. Record these findings in the wiki.

Done when 10 learning/memory resources and findings are documented.

**Comment by jacobdierkens** [comment]
Some Links:

http://www.babbel.com/magazine/10-tips-from-an-expert

http://markmanson.net/foreign-language

http://omniglot.com/language/index.htm

**Comment by rsuhaibani** [comment]
Here is a link for how to remember things better:
http://www.wikihow.com/Remember-Things-You-Study-Better 
And here is another link for how to memorize things quickly: 
http://www.lifehack.org/articles/productivity/how-memorize-things-quicker-than-other-people.html
A nice quiz that measures how is your memory holding up is presented here:
http://www.webmd.com/healthy-aging/rm-quiz-memory
Eight ways to remember anything are on this link:
https://www.psychologytoday.com/blog/happiness-in-world/200911/eight-ways-remember-anything

**Comment by dverhas** [comment]
@rsuhaibani, @jacobdierkens I combined these links into 1 wiki page in the wiki portion of github.

Thank you for the research.

**Comment by jacobdierkens** [comment]
Thanks David!
