### ISSUE TITLE
Practice Section

### ISSUE THREAD

**Issue by rsuhaibani** [FrozenSquirrels/polyglot#8]
We saw the first attempt that has been done by @nathanbreitsch 
Me and @hananmuhajab are working on the practice part
The expected date to finish this part is next week
Everybody is welcomed to add any suggestions for the questions type [multiple choice, fill in the blank, True and False]...

**Comment by nathanbreitsch** [comment]
@rsuhaibani, the practice part is not an independent feature, but a mode in which the app can be used.  A lot of the work you do on the practice part will most likely apply to the lessons as well which in other language learning apps consist of prompts to the user.  In fact, the code that allows practice mode will probably make up most of the code in the entire app.  It is therefore very important that you write the practice problems in an extensible way that does not block other developers from making progress.

The method I had envisioned was to define each problem type with a python class and a javascript class.    The advantage is that different problem types may be implemented independently.  The example problem type simply shows two words and lets the user click a button to continue.

The python class:

class BasicPrompt(Base):
    #associate class with table name
    __tablename__ = 'basic_promt'
    #define fields
    english = Column(String(80), nullable = False)
    hindi = Column(String(80), nullable = False)
    id = Column(Integer, primary_key = True)

The javascript class:

function BasicPrompt(promptData){
    var self = this;
    self.hindi = promptData.hindi;
    self.english = promptData.english;
}

Suppose you were to add a multiple choice question type.  You can achieve this by writing new versions of the above classes (called MultipleChoicePrompt) and giving them the proper data (question, choices, correct answer).  You can then follow the example code to get data out of the database, down to the client, and bound to html.

Of course, you are free to use a different architecture if you think of a better way.  But please make sure whatever method you use may be easily extended to add new question types and functionality and is easily testable.

Another strategy would be to make the html/css now and decide how to handle data later.

Keep me updated.  I'm excited to see what you come up with.

**Comment by rsuhaibani** [comment]
@nathanbreitsch I appreciate what you have written.
I have some tasks that I need to finish at this moment. I will see later what architecture I will follow and  keep you updated about this for sure.

**Comment by hananmuhajab** [comment]
@nathanbreitsch $ @rsuhaibani ..I work  to design login system to allow some permissions for  each member in our group [ check -add- delete] in practice test.
thanks for your cooperation.

**Comment by nathanbreitsch** [comment]
Hanan, 

David and I have something good going for the practice section so we will take over that feature.  Once complete (this week) it will allow the easy addition of different question types.  We will use mongo, knockoutjs, and bottle.  I will leverage the code you sent me for multiple choice.

**Comment by nathanbreitsch** [comment]
I am now splitting this issue into smaller pieces and closing it.

**Comment by hananmuhajab** [comment]
Ok ..Sound's good
